export const salesForecast = [
    {
        "date": "2023-02-05 00:00:00.0",
        "location": "Hamburg",
        "forecasted_sales_quantity": 394.1765034648572
    },
    {
        "date": "2023-02-06 00:00:00.0",
        "location": "Hamburg",
        "forecasted_sales_quantity": 479.01574214914166
    },
    {
        "date": "2023-02-07 00:00:00.0",
        "location": "Hamburg",
        "forecasted_sales_quantity": 825.0401938883233
    }
];

export const weatherForecast = {
    "queryCost": 1,
    "latitude": 52.516,
    "longitude": 13.3769,
    "resolvedAddress": "Berlin, Deutschland",
    "address": "Berlin",
    "timezone": "Europe/Berlin",
    "tzoffset": 1.0,
    "description": "Similar temperatures continuing with no rain expected.",
    "days": [
        {
            "datetime": "2023-02-05",
            "datetimeEpoch": 1675551600,
            "tempmax": 0.5,
            "tempmin": -6.0,
            "temp": -2.4,
            "feelslikemax": -1.2,
            "feelslikemin": -9.7,
            "feelslike": -3.8,
            "dew": -5.3,
            "humidity": 81.4,
            "precip": 0.0,
            "precipprob": 0.0,
            "precipcover": 0.0,
            "preciptype": null,
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 21.6,
            "windspeed": 9.0,
            "winddir": 145.8,
            "pressure": 1038.1,
            "cloudcover": 68.6,
            "visibility": 17.1,
            "solarradiation": 44.5,
            "solarenergy": 3.9,
            "uvindex": 2.0,
            "severerisk": 10.0,
            "sunrise": "07:42:08",
            "sunriseEpoch": 1675579328,
            "sunset": "16:59:36",
            "sunsetEpoch": 1675612776,
            "moonphase": 0.5,
            "conditions": "Partially cloudy",
            "description": "Partly cloudy throughout the day.",
            "icon": "partly-cloudy-day",
            "stations": [
                "EDDB",
                "E2835"
            ],
            "source": "comb",
            "hours": [
                {
                    "datetime": "00:00:00",
                    "datetimeEpoch": 1675551600,
                    "temp": -4.0,
                    "feelslike": -4.0,
                    "humidity": 85.96,
                    "dew": -6.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.4,
                    "windspeed": 1.8,
                    "winddir": 32.0,
                    "pressure": 1040.0,
                    "visibility": 10.0,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": [
                        "EDDB"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "01:00:00",
                    "datetimeEpoch": 1675555200,
                    "temp": -3.0,
                    "feelslike": -3.0,
                    "humidity": 79.78,
                    "dew": -6.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 6.5,
                    "windspeed": 2.2,
                    "winddir": 14.4,
                    "pressure": 1040.0,
                    "visibility": 10.0,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": [
                        "EDDB"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "02:00:00",
                    "datetimeEpoch": 1675558800,
                    "temp": -4.0,
                    "feelslike": -4.0,
                    "humidity": 85.96,
                    "dew": -6.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 5.0,
                    "windspeed": 1.8,
                    "winddir": 33.1,
                    "pressure": 1040.0,
                    "visibility": 10.0,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": [
                        "EDDB"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "03:00:00",
                    "datetimeEpoch": 1675562400,
                    "temp": -4.0,
                    "feelslike": -6.4,
                    "humidity": 85.96,
                    "dew": -6.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 2.5,
                    "windspeed": 5.4,
                    "winddir": 240.0,
                    "pressure": 1039.0,
                    "visibility": 10.0,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": [
                        "EDDB"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "04:00:00",
                    "datetimeEpoch": 1675566000,
                    "temp": -6.0,
                    "feelslike": -6.0,
                    "humidity": 92.63,
                    "dew": -7.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 4.7,
                    "windspeed": 2.2,
                    "winddir": 194.5,
                    "pressure": 1038.0,
                    "visibility": 10.0,
                    "cloudcover": 4.1,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": [
                        "EDDB"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "05:00:00",
                    "datetimeEpoch": 1675569600,
                    "temp": -6.0,
                    "feelslike": -9.7,
                    "humidity": 92.63,
                    "dew": -7.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 5.8,
                    "windspeed": 7.6,
                    "winddir": 260.0,
                    "pressure": 1038.0,
                    "visibility": 10.0,
                    "cloudcover": 65.4,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": [
                        "EDDB"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "06:00:00",
                    "datetimeEpoch": 1675573200,
                    "temp": -5.0,
                    "feelslike": -5.0,
                    "humidity": 85.85,
                    "dew": -7.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 6.1,
                    "windspeed": 1.8,
                    "winddir": 189.7,
                    "pressure": 1038.0,
                    "visibility": 10.0,
                    "cloudcover": 84.8,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": [
                        "EDDB"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "07:00:00",
                    "datetimeEpoch": 1675576800,
                    "temp": -5.0,
                    "feelslike": -5.0,
                    "humidity": 92.69,
                    "dew": -6.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.6,
                    "windspeed": 3.2,
                    "winddir": 179.0,
                    "pressure": 1038.0,
                    "visibility": 10.0,
                    "cloudcover": 100.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": [
                        "EDDB"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "08:00:00",
                    "datetimeEpoch": 1675580400,
                    "temp": -5.0,
                    "feelslike": -5.0,
                    "humidity": 92.69,
                    "dew": -6.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.7,
                    "windspeed": 3.6,
                    "winddir": 160.4,
                    "pressure": 1038.0,
                    "visibility": 10.0,
                    "cloudcover": 100.0,
                    "solarradiation": 12.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": [
                        "EDDB",
                        "E2835"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "09:00:00",
                    "datetimeEpoch": 1675584000,
                    "temp": -4.0,
                    "feelslike": -7.3,
                    "humidity": 92.75,
                    "dew": -5.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 11.5,
                    "windspeed": 7.6,
                    "winddir": 110.0,
                    "pressure": 1038.0,
                    "visibility": 10.0,
                    "cloudcover": 94.4,
                    "solarradiation": 32.0,
                    "solarenergy": 0.1,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": [
                        "EDDB",
                        "E2835"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "10:00:00",
                    "datetimeEpoch": 1675587600,
                    "temp": -3.0,
                    "feelslike": -3.0,
                    "humidity": 86.07,
                    "dew": -5.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 14.8,
                    "windspeed": 6.1,
                    "winddir": 153.6,
                    "pressure": 1038.0,
                    "visibility": 10.0,
                    "cloudcover": 100.0,
                    "solarradiation": 80.0,
                    "solarenergy": 0.3,
                    "uvindex": 1.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": [
                        "EDDB",
                        "E2835"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "11:00:00",
                    "datetimeEpoch": 1675591200,
                    "temp": -2.0,
                    "feelslike": -5.0,
                    "humidity": 86.18,
                    "dew": -4.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 17.3,
                    "windspeed": 7.6,
                    "winddir": 140.0,
                    "pressure": 1038.0,
                    "visibility": 10.0,
                    "cloudcover": 100.0,
                    "solarradiation": 107.0,
                    "solarenergy": 0.4,
                    "uvindex": 1.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": [
                        "EDDB",
                        "E2835"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "12:00:00",
                    "datetimeEpoch": 1675594800,
                    "temp": -0.5,
                    "feelslike": -3.5,
                    "humidity": 67.9,
                    "dew": -5.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 20.9,
                    "windspeed": 8.3,
                    "winddir": 144.8,
                    "pressure": 1037.0,
                    "visibility": 24.1,
                    "cloudcover": 100.0,
                    "solarradiation": 203.0,
                    "solarenergy": 0.7,
                    "uvindex": 2.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "13:00:00",
                    "datetimeEpoch": 1675598400,
                    "temp": 0.2,
                    "feelslike": -2.7,
                    "humidity": 64.54,
                    "dew": -5.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 21.2,
                    "windspeed": 8.6,
                    "winddir": 147.0,
                    "pressure": 1037.0,
                    "visibility": 24.1,
                    "cloudcover": 100.0,
                    "solarradiation": 209.0,
                    "solarenergy": 0.8,
                    "uvindex": 2.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "14:00:00",
                    "datetimeEpoch": 1675602000,
                    "temp": 0.5,
                    "feelslike": -2.5,
                    "humidity": 63.15,
                    "dew": -5.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 21.2,
                    "windspeed": 9.0,
                    "winddir": 137.5,
                    "pressure": 1037.0,
                    "visibility": 24.1,
                    "cloudcover": 100.0,
                    "solarradiation": 187.0,
                    "solarenergy": 0.7,
                    "uvindex": 2.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "15:00:00",
                    "datetimeEpoch": 1675605600,
                    "temp": 0.5,
                    "feelslike": -2.5,
                    "humidity": 63.15,
                    "dew": -5.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 21.6,
                    "windspeed": 9.0,
                    "winddir": 137.2,
                    "pressure": 1037.0,
                    "visibility": 24.1,
                    "cloudcover": 100.0,
                    "solarradiation": 142.0,
                    "solarenergy": 0.5,
                    "uvindex": 1.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "16:00:00",
                    "datetimeEpoch": 1675609200,
                    "temp": 0.3,
                    "feelslike": -2.2,
                    "humidity": 66.05,
                    "dew": -5.3,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 20.9,
                    "windspeed": 7.2,
                    "winddir": 134.2,
                    "pressure": 1037.0,
                    "visibility": 24.1,
                    "cloudcover": 99.9,
                    "solarradiation": 74.0,
                    "solarenergy": 0.3,
                    "uvindex": 1.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "17:00:00",
                    "datetimeEpoch": 1675612800,
                    "temp": -0.1,
                    "feelslike": -2.4,
                    "humidity": 71.15,
                    "dew": -4.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 16.9,
                    "windspeed": 6.5,
                    "winddir": 130.0,
                    "pressure": 1037.0,
                    "visibility": 24.1,
                    "cloudcover": 100.0,
                    "solarradiation": 22.0,
                    "solarenergy": 0.1,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "18:00:00",
                    "datetimeEpoch": 1675616400,
                    "temp": -0.5,
                    "feelslike": -2.2,
                    "humidity": 76.63,
                    "dew": -4.1,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 15.1,
                    "windspeed": 5.0,
                    "winddir": 129.3,
                    "pressure": 1037.0,
                    "visibility": 24.1,
                    "cloudcover": 100.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "19:00:00",
                    "datetimeEpoch": 1675620000,
                    "temp": -0.9,
                    "feelslike": -3.1,
                    "humidity": 80.69,
                    "dew": -3.8,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 13.7,
                    "windspeed": 6.1,
                    "winddir": 132.8,
                    "pressure": 1038.0,
                    "visibility": 24.1,
                    "cloudcover": 97.4,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "20:00:00",
                    "datetimeEpoch": 1675623600,
                    "temp": -1.2,
                    "feelslike": -1.2,
                    "humidity": 82.48,
                    "dew": -3.8,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 13.7,
                    "windspeed": 4.7,
                    "winddir": 149.6,
                    "pressure": 1038.0,
                    "visibility": 24.1,
                    "cloudcover": 98.4,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "21:00:00",
                    "datetimeEpoch": 1675627200,
                    "temp": -1.5,
                    "feelslike": -1.5,
                    "humidity": 84.32,
                    "dew": -3.8,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 11.2,
                    "windspeed": 4.3,
                    "winddir": 144.0,
                    "pressure": 1038.0,
                    "visibility": 24.1,
                    "cloudcover": 35.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "22:00:00",
                    "datetimeEpoch": 1675630800,
                    "temp": -2.0,
                    "feelslike": -2.0,
                    "humidity": 86.83,
                    "dew": -3.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.4,
                    "windspeed": 2.9,
                    "winddir": 150.4,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 60.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "23:00:00",
                    "datetimeEpoch": 1675634400,
                    "temp": -2.4,
                    "feelslike": -2.4,
                    "humidity": 87.44,
                    "dew": -4.2,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.2,
                    "windspeed": 2.5,
                    "winddir": 139.4,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 7.1,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                }
            ]
        },
        {
            "datetime": "2023-02-06",
            "datetimeEpoch": 1675638000,
            "tempmax": 0.0,
            "tempmin": -3.7,
            "temp": -2.1,
            "feelslikemax": 0.0,
            "feelslikemin": -3.7,
            "feelslike": -2.1,
            "dew": -4.7,
            "humidity": 82.6,
            "precip": 0.1,
            "precipprob": 4.8,
            "precipcover": 4.17,
            "preciptype": [
                "rain",
                "snow"
            ],
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 13.7,
            "windspeed": 4.3,
            "winddir": 97.8,
            "pressure": 1039.4,
            "cloudcover": 41.5,
            "visibility": 24.1,
            "solarradiation": 73.1,
            "solarenergy": 6.3,
            "uvindex": 3.0,
            "severerisk": 10.0,
            "sunrise": "07:40:23",
            "sunriseEpoch": 1675665623,
            "sunset": "17:01:30",
            "sunsetEpoch": 1675699290,
            "moonphase": 0.5,
            "conditions": "Partially cloudy",
            "description": "Partly cloudy throughout the day.",
            "icon": "partly-cloudy-day",
            "stations": null,
            "source": "fcst",
            "hours": [
                {
                    "datetime": "00:00:00",
                    "datetimeEpoch": 1675638000,
                    "temp": -2.8,
                    "feelslike": -2.8,
                    "humidity": 88.73,
                    "dew": -4.4,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.4,
                    "windspeed": 4.3,
                    "winddir": 141.3,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "01:00:00",
                    "datetimeEpoch": 1675641600,
                    "temp": -3.1,
                    "feelslike": -3.1,
                    "humidity": 88.7,
                    "dew": -4.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 10.1,
                    "windspeed": 4.0,
                    "winddir": 153.3,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "02:00:00",
                    "datetimeEpoch": 1675645200,
                    "temp": -3.2,
                    "feelslike": -3.2,
                    "humidity": 87.36,
                    "dew": -5.0,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 8.6,
                    "windspeed": 3.2,
                    "winddir": 159.3,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "03:00:00",
                    "datetimeEpoch": 1675648800,
                    "temp": -3.4,
                    "feelslike": -3.4,
                    "humidity": 87.34,
                    "dew": -5.2,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 6.8,
                    "windspeed": 2.9,
                    "winddir": 156.8,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "04:00:00",
                    "datetimeEpoch": 1675652400,
                    "temp": -3.5,
                    "feelslike": -3.5,
                    "humidity": 86.02,
                    "dew": -5.5,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.0,
                    "windspeed": 4.3,
                    "winddir": 150.9,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 5.9,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "05:00:00",
                    "datetimeEpoch": 1675656000,
                    "temp": -3.6,
                    "feelslike": -3.6,
                    "humidity": 85.35,
                    "dew": -5.7,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.0,
                    "windspeed": 3.6,
                    "winddir": 157.7,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 51.1,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "06:00:00",
                    "datetimeEpoch": 1675659600,
                    "temp": -3.7,
                    "feelslike": -3.7,
                    "humidity": 85.34,
                    "dew": -5.8,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.9,
                    "windspeed": 2.5,
                    "winddir": 161.4,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 51.8,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "07:00:00",
                    "datetimeEpoch": 1675663200,
                    "temp": -3.7,
                    "feelslike": -3.7,
                    "humidity": 84.7,
                    "dew": -5.9,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 5.8,
                    "windspeed": 2.5,
                    "winddir": 169.7,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 66.6,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "08:00:00",
                    "datetimeEpoch": 1675666800,
                    "temp": -3.5,
                    "feelslike": -3.5,
                    "humidity": 83.44,
                    "dew": -5.9,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 6.1,
                    "windspeed": 2.5,
                    "winddir": 186.2,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 100.0,
                    "solarradiation": 2.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "09:00:00",
                    "datetimeEpoch": 1675670400,
                    "temp": -2.9,
                    "feelslike": -2.9,
                    "humidity": 79.79,
                    "dew": -5.9,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 6.5,
                    "windspeed": 2.2,
                    "winddir": 161.2,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 100.0,
                    "solarradiation": 55.0,
                    "solarenergy": 0.2,
                    "uvindex": 1.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "10:00:00",
                    "datetimeEpoch": 1675674000,
                    "temp": -2.2,
                    "feelslike": -2.2,
                    "humidity": 78.1,
                    "dew": -5.5,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 6.5,
                    "windspeed": 1.1,
                    "winddir": 172.2,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 94.3,
                    "solarradiation": 169.0,
                    "solarenergy": 0.6,
                    "uvindex": 2.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "11:00:00",
                    "datetimeEpoch": 1675677600,
                    "temp": -1.5,
                    "feelslike": -1.5,
                    "humidity": 74.17,
                    "dew": -5.5,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.2,
                    "windspeed": 2.5,
                    "winddir": 76.2,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 94.0,
                    "solarradiation": 254.0,
                    "solarenergy": 0.9,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "12:00:00",
                    "datetimeEpoch": 1675681200,
                    "temp": -1.0,
                    "feelslike": -1.0,
                    "humidity": 73.71,
                    "dew": -5.1,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 10.4,
                    "windspeed": 4.0,
                    "winddir": 76.4,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 90.8,
                    "solarradiation": 287.0,
                    "solarenergy": 1.0,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "13:00:00",
                    "datetimeEpoch": 1675684800,
                    "temp": -0.9,
                    "feelslike": -0.9,
                    "humidity": 77.72,
                    "dew": -4.3,
                    "precip": 0.0,
                    "precipprob": 4.8,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 11.9,
                    "windspeed": 3.2,
                    "winddir": 67.3,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 83.5,
                    "solarradiation": 294.0,
                    "solarenergy": 1.1,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "14:00:00",
                    "datetimeEpoch": 1675688400,
                    "temp": -0.4,
                    "feelslike": -0.4,
                    "humidity": 76.65,
                    "dew": -4.0,
                    "precip": 0.1,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": [
                        "rain",
                        "snow"
                    ],
                    "windgust": 10.1,
                    "windspeed": 3.6,
                    "winddir": 34.2,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 78.5,
                    "solarradiation": 265.0,
                    "solarenergy": 1.0,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "15:00:00",
                    "datetimeEpoch": 1675692000,
                    "temp": -0.1,
                    "feelslike": -0.1,
                    "humidity": 75.56,
                    "dew": -3.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 11.5,
                    "windspeed": 4.3,
                    "winddir": 40.4,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 82.0,
                    "solarradiation": 252.0,
                    "solarenergy": 0.9,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "16:00:00",
                    "datetimeEpoch": 1675695600,
                    "temp": 0.0,
                    "feelslike": 0.0,
                    "humidity": 76.14,
                    "dew": -3.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 13.7,
                    "windspeed": 4.0,
                    "winddir": 40.3,
                    "pressure": 1039.0,
                    "visibility": 24.1,
                    "cloudcover": 70.1,
                    "solarradiation": 144.0,
                    "solarenergy": 0.5,
                    "uvindex": 1.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "17:00:00",
                    "datetimeEpoch": 1675699200,
                    "temp": -0.2,
                    "feelslike": -0.2,
                    "humidity": 79.6,
                    "dew": -3.3,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.7,
                    "windspeed": 4.0,
                    "winddir": 16.3,
                    "pressure": 1040.0,
                    "visibility": 24.1,
                    "cloudcover": 13.6,
                    "solarradiation": 33.0,
                    "solarenergy": 0.1,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "18:00:00",
                    "datetimeEpoch": 1675702800,
                    "temp": -0.7,
                    "feelslike": -0.7,
                    "humidity": 86.32,
                    "dew": -2.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.0,
                    "windspeed": 3.6,
                    "winddir": 21.8,
                    "pressure": 1040.0,
                    "visibility": 24.1,
                    "cloudcover": 13.6,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "19:00:00",
                    "datetimeEpoch": 1675706400,
                    "temp": -1.1,
                    "feelslike": -1.1,
                    "humidity": 88.88,
                    "dew": -2.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.6,
                    "windspeed": 3.6,
                    "winddir": 62.4,
                    "pressure": 1040.0,
                    "visibility": 24.1,
                    "cloudcover": 1.1,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "20:00:00",
                    "datetimeEpoch": 1675710000,
                    "temp": -1.5,
                    "feelslike": -1.5,
                    "humidity": 84.95,
                    "dew": -3.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.9,
                    "windspeed": 3.6,
                    "winddir": 70.6,
                    "pressure": 1040.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "21:00:00",
                    "datetimeEpoch": 1675713600,
                    "temp": -2.0,
                    "feelslike": -2.0,
                    "humidity": 83.63,
                    "dew": -4.4,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.9,
                    "windspeed": 3.6,
                    "winddir": 64.7,
                    "pressure": 1041.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "22:00:00",
                    "datetimeEpoch": 1675717200,
                    "temp": -2.4,
                    "feelslike": -2.4,
                    "humidity": 84.21,
                    "dew": -4.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.9,
                    "windspeed": 3.6,
                    "winddir": 76.6,
                    "pressure": 1041.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "23:00:00",
                    "datetimeEpoch": 1675720800,
                    "temp": -2.7,
                    "feelslike": -2.7,
                    "humidity": 85.46,
                    "dew": -4.8,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.9,
                    "windspeed": 3.6,
                    "winddir": 104.8,
                    "pressure": 1041.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                }
            ]
        },
        {
            "datetime": "2023-02-07",
            "datetimeEpoch": 1675724400,
            "tempmax": 0.7,
            "tempmin": -4.5,
            "temp": -2.1,
            "feelslikemax": 0.7,
            "feelslikemin": -4.5,
            "feelslike": -2.1,
            "dew": -5.8,
            "humidity": 76.8,
            "precip": 0.0,
            "precipprob": 0.0,
            "precipcover": 0.0,
            "preciptype": null,
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 9.4,
            "windspeed": 3.6,
            "winddir": 100.4,
            "pressure": 1042.5,
            "cloudcover": 9.9,
            "visibility": 24.1,
            "solarradiation": 85.5,
            "solarenergy": 7.3,
            "uvindex": 4.0,
            "severerisk": 10.0,
            "sunrise": "07:38:37",
            "sunriseEpoch": 1675751917,
            "sunset": "17:03:25",
            "sunsetEpoch": 1675785805,
            "moonphase": 0.52,
            "conditions": "Clear",
            "description": "Clear conditions throughout the day.",
            "icon": "clear-day",
            "stations": null,
            "source": "fcst",
            "hours": [
                {
                    "datetime": "00:00:00",
                    "datetimeEpoch": 1675724400,
                    "temp": -3.1,
                    "feelslike": -3.1,
                    "humidity": 87.37,
                    "dew": -4.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.9,
                    "windspeed": 3.6,
                    "winddir": 124.9,
                    "pressure": 1041.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "01:00:00",
                    "datetimeEpoch": 1675728000,
                    "temp": -3.3,
                    "feelslike": -3.3,
                    "humidity": 87.35,
                    "dew": -5.1,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.6,
                    "windspeed": 2.5,
                    "winddir": 89.0,
                    "pressure": 1042.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "02:00:00",
                    "datetimeEpoch": 1675731600,
                    "temp": -3.4,
                    "feelslike": -3.4,
                    "humidity": 86.68,
                    "dew": -5.3,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 4.7,
                    "windspeed": 1.8,
                    "winddir": 101.7,
                    "pressure": 1042.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "03:00:00",
                    "datetimeEpoch": 1675735200,
                    "temp": -3.6,
                    "feelslike": -3.6,
                    "humidity": 86.66,
                    "dew": -5.5,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 3.6,
                    "windspeed": 2.2,
                    "winddir": 91.7,
                    "pressure": 1042.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "04:00:00",
                    "datetimeEpoch": 1675738800,
                    "temp": -3.8,
                    "feelslike": -3.8,
                    "humidity": 86.64,
                    "dew": -5.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 3.6,
                    "windspeed": 2.2,
                    "winddir": 91.3,
                    "pressure": 1042.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "05:00:00",
                    "datetimeEpoch": 1675742400,
                    "temp": -4.0,
                    "feelslike": -4.0,
                    "humidity": 87.28,
                    "dew": -5.8,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 4.7,
                    "windspeed": 2.9,
                    "winddir": 69.2,
                    "pressure": 1042.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "06:00:00",
                    "datetimeEpoch": 1675746000,
                    "temp": -4.2,
                    "feelslike": -4.2,
                    "humidity": 87.93,
                    "dew": -5.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 5.4,
                    "windspeed": 2.2,
                    "winddir": 63.1,
                    "pressure": 1042.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "07:00:00",
                    "datetimeEpoch": 1675749600,
                    "temp": -4.3,
                    "feelslike": -4.3,
                    "humidity": 87.92,
                    "dew": -6.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 4.0,
                    "windspeed": 2.5,
                    "winddir": 80.3,
                    "pressure": 1042.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "08:00:00",
                    "datetimeEpoch": 1675753200,
                    "temp": -4.5,
                    "feelslike": -4.5,
                    "humidity": 87.9,
                    "dew": -6.2,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 5.4,
                    "windspeed": 3.2,
                    "winddir": 104.8,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 2.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "09:00:00",
                    "datetimeEpoch": 1675756800,
                    "temp": -4.4,
                    "feelslike": -4.4,
                    "humidity": 87.91,
                    "dew": -6.1,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 5.4,
                    "windspeed": 1.8,
                    "winddir": 151.0,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 73.0,
                    "solarenergy": 0.3,
                    "uvindex": 1.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "10:00:00",
                    "datetimeEpoch": 1675760400,
                    "temp": -3.3,
                    "feelslike": -3.3,
                    "humidity": 83.46,
                    "dew": -5.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 6.1,
                    "windspeed": 2.5,
                    "winddir": 176.8,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 196.0,
                    "solarenergy": 0.7,
                    "uvindex": 2.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "11:00:00",
                    "datetimeEpoch": 1675764000,
                    "temp": -2.1,
                    "feelslike": -2.1,
                    "humidity": 75.2,
                    "dew": -5.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.4,
                    "windspeed": 3.2,
                    "winddir": 158.1,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 286.0,
                    "solarenergy": 1.0,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "12:00:00",
                    "datetimeEpoch": 1675767600,
                    "temp": -0.9,
                    "feelslike": -0.9,
                    "humidity": 67.3,
                    "dew": -6.2,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.4,
                    "windspeed": 3.2,
                    "winddir": 163.5,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 355.0,
                    "solarenergy": 1.3,
                    "uvindex": 4.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "13:00:00",
                    "datetimeEpoch": 1675771200,
                    "temp": 0.0,
                    "feelslike": 0.0,
                    "humidity": 63.03,
                    "dew": -6.2,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.0,
                    "windspeed": 0.7,
                    "winddir": 171.3,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 373.0,
                    "solarenergy": 1.3,
                    "uvindex": 4.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "14:00:00",
                    "datetimeEpoch": 1675774800,
                    "temp": 0.6,
                    "feelslike": 0.6,
                    "humidity": 55.89,
                    "dew": -7.2,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 3.6,
                    "windspeed": 0.7,
                    "winddir": 20.3,
                    "pressure": 1042.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 339.0,
                    "solarenergy": 1.2,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "15:00:00",
                    "datetimeEpoch": 1675778400,
                    "temp": 0.7,
                    "feelslike": 0.7,
                    "humidity": 56.35,
                    "dew": -7.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 5.4,
                    "windspeed": 1.8,
                    "winddir": 40.1,
                    "pressure": 1042.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 236.0,
                    "solarenergy": 0.8,
                    "uvindex": 2.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "16:00:00",
                    "datetimeEpoch": 1675782000,
                    "temp": 0.5,
                    "feelslike": 0.5,
                    "humidity": 61.25,
                    "dew": -6.1,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 5.4,
                    "windspeed": 2.2,
                    "winddir": 70.6,
                    "pressure": 1042.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 156.0,
                    "solarenergy": 0.6,
                    "uvindex": 2.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "17:00:00",
                    "datetimeEpoch": 1675785600,
                    "temp": 0.1,
                    "feelslike": 0.1,
                    "humidity": 65.5,
                    "dew": -5.6,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 4.7,
                    "windspeed": 2.2,
                    "winddir": 66.1,
                    "pressure": 1042.0,
                    "visibility": 24.1,
                    "cloudcover": 0.0,
                    "solarradiation": 36.0,
                    "solarenergy": 0.1,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "18:00:00",
                    "datetimeEpoch": 1675789200,
                    "temp": -0.5,
                    "feelslike": -0.5,
                    "humidity": 67.9,
                    "dew": -5.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 5.4,
                    "windspeed": 2.9,
                    "winddir": 48.0,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 0.5,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "19:00:00",
                    "datetimeEpoch": 1675792800,
                    "temp": -0.8,
                    "feelslike": -0.8,
                    "humidity": 68.88,
                    "dew": -5.8,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 5.8,
                    "windspeed": 2.9,
                    "winddir": 53.7,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 86.4,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "20:00:00",
                    "datetimeEpoch": 1675796400,
                    "temp": -1.2,
                    "feelslike": -1.2,
                    "humidity": 71.46,
                    "dew": -5.7,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 5.4,
                    "windspeed": 2.5,
                    "winddir": 77.7,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 1.2,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "21:00:00",
                    "datetimeEpoch": 1675800000,
                    "temp": -1.5,
                    "feelslike": -1.5,
                    "humidity": 74.17,
                    "dew": -5.5,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 4.3,
                    "windspeed": 2.5,
                    "winddir": 122.0,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 9.0,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "22:00:00",
                    "datetimeEpoch": 1675803600,
                    "temp": -1.9,
                    "feelslike": -1.9,
                    "humidity": 77.56,
                    "dew": -5.3,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 4.0,
                    "windspeed": 2.5,
                    "winddir": 120.9,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 97.2,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "23:00:00",
                    "datetimeEpoch": 1675807200,
                    "temp": -2.3,
                    "feelslike": -2.3,
                    "humidity": 81.1,
                    "dew": -5.1,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 4.7,
                    "windspeed": 2.9,
                    "winddir": 124.5,
                    "pressure": 1043.0,
                    "visibility": 24.1,
                    "cloudcover": 42.9,
                    "solarradiation": 0.0,
                    "solarenergy": null,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                }
            ]
        }
    ],
    "alerts": [],
    "stations": {
        "C6421": {
            "distance": 3799.0,
            "latitude": 52.532,
            "longitude": 13.427,
            "useCount": 0,
            "id": "C6421",
            "name": "CW6421 Berlin DE",
            "quality": 0,
            "contribution": 0.0
        },
        "ETSH": {
            "distance": 84127.0,
            "latitude": 51.77,
            "longitude": 13.18,
            "useCount": 0,
            "id": "ETSH",
            "name": "ETSH",
            "quality": 2,
            "contribution": 0.0
        },
        "EDDB": {
            "distance": 17985.0,
            "latitude": 52.38,
            "longitude": 13.52,
            "useCount": 0,
            "id": "EDDB",
            "name": "EDDB",
            "quality": 50,
            "contribution": 0.0
        },
        "E2835": {
            "distance": 11812.0,
            "latitude": 52.412,
            "longitude": 13.34,
            "useCount": 0,
            "id": "E2835",
            "name": "EW2835 Berlin DE",
            "quality": 0,
            "contribution": 0.0
        }
    },
    "currentConditions": {
        "datetime": "12:15:31",
        "datetimeEpoch": 1675595731,
        "temp": 0.5,
        "feelslike": -2.9,
        "humidity": 75.9,
        "dew": -3.2,
        "precip": 0.0,
        "precipprob": 0.0,
        "snow": 0.0,
        "snowdepth": 0.0,
        "preciptype": null,
        "windgust": null,
        "windspeed": 11.1,
        "winddir": 149.0,
        "pressure": 1037.0,
        "visibility": 10.0,
        "cloudcover": 88.0,
        "solarradiation": 203.0,
        "solarenergy": 0.7,
        "uvindex": 2.0,
        "conditions": "Partially cloudy",
        "icon": "partly-cloudy-day",
        "stations": [
            "ETSH",
            "C6421",
            "EDDB"
        ],
        "source": "obs",
        "sunrise": "07:42:08",
        "sunriseEpoch": 1675579328,
        "sunset": "16:59:36",
        "sunsetEpoch": 1675612776,
        "moonphase": 0.5
    }
};